<?xml version="1.0" encoding="UTF-8"?>
<testng-results ignored="2" total="3" passed="0" failed="1" skipped="0">
  <reporter-output>
  </reporter-output>
  <suite started-at="2024-12-27T08:48:13 IST" name="Default suite" finished-at="2024-12-27T08:48:21 IST" duration-ms="7851">
    <groups>
    </groups>
    <test started-at="2024-12-27T08:48:13 IST" name="Default test" finished-at="2024-12-27T08:48:21 IST" duration-ms="7851">
      <class name="mtestcases.TC_PLC">
        <test-method is-config="true" signature="baseSetUp()[pri:0, instance:mtestcases.TC_PLC@51c668e3]" started-at="2024-12-27T08:48:13 IST" name="baseSetUp" finished-at="2024-12-27T08:48:13 IST" duration-ms="5" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- baseSetUp -->
        <test-method is-config="true" signature="incrementSessionId()[pri:0, instance:mtestcases.TC_PLC@51c668e3]" started-at="2024-12-27T08:48:13 IST" name="incrementSessionId" finished-at="2024-12-27T08:48:13 IST" duration-ms="0" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- incrementSessionId -->
        <test-method signature="PLC_RefundOfSale()[pri:0, instance:mtestcases.TC_PLC@51c668e3]" started-at="2024-12-27T08:48:13 IST" name="PLC_RefundOfSale" finished-at="2024-12-27T08:48:18 IST" duration-ms="5813" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[Get Card Bin Request denied!]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: Get Card Bin Request denied!
at org.testng.Assert.fail(Assert.java:99)
at base.BaseClass.performGetCardBin(BaseClass.java:182)
at base.BaseClass.performPLCSale(BaseClass.java:473)
at mtestcases.TC_PLC.PLC_RefundOfSale(TC_PLC.java:21)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:293)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:91)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- PLC_RefundOfSale -->
        <test-method is-config="true" signature="saveXLFile()[pri:0, instance:mtestcases.TC_PLC@51c668e3]" started-at="2024-12-27T08:48:19 IST" name="saveXLFile" finished-at="2024-12-27T08:48:21 IST" duration-ms="2006" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- saveXLFile -->
      </class> <!-- mtestcases.TC_PLC -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
